### ISSUE TITLE
使用 exec 来获取 git 信息时可能会出现 ERR_CHILD_PROCESS_STDIO_MAXBUFFER 问题

### ISSUE THREAD

**Issue by helinjiang** [matmanjs/incremental-coverage#8]
```
- { RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
-           at Socket.onChildStdout (child_process.js:354:14)
-           at Socket.emit (events.js:198:13)
-           at addChunk (_stream_readable.js:288:12)
-           at readableAddChunk (_stream_readable.js:265:13)
-           at Socket.Readable.push (_stream_readable.js:224:10)
-           at Pipe.onStreamRead (internal/stream_base_commons.js:94:17) cmd: 'git diff 401b28c50ac1176910dd795ecbbce5bc9ad2bb08' }
```

**Comment by helinjiang** [comment]
参考 https://stackoverflow.com/questions/23429499/stdout-buffer-issue-using-node-child-process 

使用 `git diff` 命令之后，输出太多，导致超过了限制，需要替换为 `spawn`
